# -*- coding: utf-8 -*-
"""Журке КП6_DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNyK9tJBufIxJTXYZQT-l9xY_zd5RfpB

<center><font size="6"><b>Комп'ютерний практикум 6.

<center><b> Створення дашборду за допомогою Streamlit </font>

##<center>__Самостійні завдання__</center>

> Скопіювати блок самостійних завдань в окремий файл ***LastName_DA6.py***

> Інсталюйте необхідні пакети бібліотек Python збережіть у файл `requirements.txt`

> завантажте файл зі статистичного банку даних, з яким будете працювати `data.csv`

### Завдання

1. Створіть dashboard, як додаток у **Streamlit Community Cloud**
2. Додаток має містити: панель фільтрації з елементами
- Заголовок      
- Текстовий опис / інструкції                       
- Один вибір зі списку                              
- Кілька виборів                                   
- Вибір одного варіанту з декількох (радіо-кнопки)  
- Прапорець        
3. В головній частині: таблиця, як результат фільтрів з можливістю вибору колонок
4. Графічне представлення (мінімум 3 типи графіки)
5. Реалізація регресійної моделі або інших (кластеризації/класифікації)                        
6. Створені файли мають бути розміщені в репрозиторії GitHub, та імплементуватися в Streamlit Community Cloud
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import plotly.express as px
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('ВВП за 2025 рік_кп6.csv')
df.info()
df.describe()
missing_data = df.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

st.set_page_config(
    page_title="Аналіз світового ВВП за 2025 рік – МВФ аналітичний дашборд(KP6)",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інтерактивна панель для аналізу показника ВВП країн за 2025 рік'
    }
)
# Функція для завантаження та очищення даних
@st.cache_data
def load_data():
    df = pd.read_csv("ВВП за 2025 рік_кп6.csv")
    # Очищення даних: видалення пробілів, заміна ком на крапки
    df['ВВП (повна вартість), $'] = df['ВВП (повна вартість), $'].astype(str).str.replace(' ', '').astype(float)
    df['Зростання ВВП, %'] = df['Зростання ВВП, %'].astype(str).str.replace(',', '.').astype(float)
    df['ВВП на душу населення, $'] = df['ВВП на душу населення, $'].astype(str).str.replace(' ', '').astype(float)
    return df

df = load_data()

# Бічна панель / SIDEBAR
st.sidebar.title("Панель налаштувань")

st.sidebar.write("Використовуйте цю панель для фільтрації та налаштування відображення даних.")

# Один вибір зі списку (Selectbox)
top_n = st.sidebar.selectbox("Показати Топ-N країн рейтингу:", [10, 20, 50, 100, len(df)], index=2)

# Кілька виборів (Multiselect)
all_countries = df['Країна'].tolist()
selected_countries = st.sidebar.multiselect("Виділити конкретні країни (для графіків):", all_countries, default=["Україна", "Польща", "Сполучені Штати"])

# Вибір одного варіанту з декількох (Radio buttons)
growth_filter = st.sidebar.radio(
    "Фільтр за економічним зростанням:",
    ("Всі країни", "Тільки зростання (> 0%)", "Тільки спад (< 0%)")
)

# Прапорець (Checkbox)
show_table = st.sidebar.checkbox("Відображати таблицю даних", value=True)

# Застосування фільтрів
filtered_df = df.head(top_n).copy()
if growth_filter == "Тільки зростання (> 0%)":
    filtered_df = filtered_df[filtered_df['Зростання ВВП, %'] > 0]
elif growth_filter == "Тільки спад (< 0%)":
    filtered_df = filtered_df[filtered_df['Зростання ВВП, %'] < 0]

# Інформаційний блок
st.sidebar.markdown("---")
st.sidebar.markdown(" **Інструкція**: \nВідфільтруйте дані за параметрами і переглядайте результат (графіки та таблиці) на панелі праворуч.")
st.sidebar.markdown(" **Автор**: Anastasiia")

# Основна панель
st.title("🌍 Аналіз макроекономічних показників (ВВП 2025)")

# ТАБЛИЦЯ З ВИБОРОМ КОЛОНОК
if show_table:
    st.subheader("📊 Дані у вигляді таблиці")
    all_columns = filtered_df.columns.tolist()
    # Вибір колонок
    selected_cols = st.multiselect("Оберіть колонки для відображення:", all_columns, default=all_columns)
    st.dataframe(filtered_df[selected_cols], use_container_width=True)

# ГРАФІЧНЕ ПРЕДСТАВЛЕННЯ (Мінімум 3 типи графіки)
st.subheader("📈 Візуалізація показників")

col1, col2 = st.columns(2)

with col1:
    # Тип 1: Стовпчаста діаграма (Bar Chart)
    fig1 = px.bar(filtered_df.head(15), x='Країна', y='ВВП (повна вартість), $',
                  title='Топ-15 країн за загальним обсягом ВВП',
                  color='ВВП (повна вартість), $', color_continuous_scale='Viridis')
    st.plotly_chart(fig1, use_container_width=True)

with col2:
    # Тип 2: Діаграма розсіювання (Scatter Plot)
    fig2 = px.scatter(filtered_df, x='ВВП на душу населення, $', y='Зростання ВВП, %',
                      hover_name='Країна', size='ВВП (повна вартість), $',
                      title='ВВП на душу населення vs Темпи зростання',
                      color_discrete_sequence=['#ef553b'])
    st.plotly_chart(fig2, use_container_width=True)

# Тип 3: Гістограма розподілу (Histogram)
fig3 = px.histogram(filtered_df, x='Зростання ВВП, %', nbins=30,
                    title='Розподіл країн за темпами зростання ВВП',
                    marginal='box', color_discrete_sequence=['#00cc96'])
st.plotly_chart(fig3, use_container_width=True)



# Кластеризація
st.markdown("---")
st.subheader("Кластеризація K-Means")
st.write("Ця модель автоматично групує країни у кластери зі схожими економічними показниками (на основі ВВП на душу населення та темпів зростання).")

# Вибір кількості кластерів користувачем
k_clusters = st.slider("Оберіть кількість кластерів (K):", min_value=2, max_value=6, value=3)

# Підготовка даних для ML
ml_df = df.dropna(subset=['ВВП на душу населення, $', 'Зростання ВВП, %']).copy()
X = ml_df[['ВВП на душу населення, $', 'Зростання ВВП, %']]

# Масштабування (стандартизація) даних
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Застосування K-Means
kmeans = KMeans(n_clusters=k_clusters, random_state=42, n_init=10)
ml_df['Кластер'] = kmeans.fit_predict(X_scaled)
# Робимо кластер текстовим для правильної кольорової легенди
ml_df['Кластер'] = ml_df['Кластер'].astype(str)

# Візуалізація результатів кластеризації
fig_ml = px.scatter(ml_df, x='ВВП на душу населення, $', y='Зростання ВВП, %',
                    color='Кластер', hover_name='Країна',
                    title=f'Результат кластеризації країн (K={k_clusters})')
st.plotly_chart(fig_ml, use_container_width=True)